# Generated by Django 2.0.2 on 2018-10-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('relatedOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_article', to='howdy.Post')),
                ('relatedThree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_article', to='howdy.Post')),
                ('relatedTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_article', to='howdy.Post')),
            ],
        ),
    ]
