# Generated by Django 2.0.2 on 2018-10-04 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_auto_20181003_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relatedOne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_article', to='howdy.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='relatedThree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_article', to='howdy.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='relatedTwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_article', to='howdy.Post'),
        ),
    ]
