# Generated by Django 2.0.2 on 2018-10-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0003_auto_20181003_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postNum',
            field=models.IntegerField(default=1),
        ),
    ]
